kind: Pod
apiVersion: v1
metadata:
  name: random
  labels:
    app: random
spec:
  containers:
    - name: random
      image: enocom/random:latest
      ports:
        - name: http
          containerPort: 80
      env:
        - name: ADDR
          value: 0.0.0.0:80
        - name: POLL_DURATION
          value: 1m
